export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const REMOVE_ALL_INGREDIENTS = "REMOVE_ALL_INGREDIENTS";
export const INGREDIENTS_FETCH_ERROR = "INGREDIENTS_FETCH_ERROR";
export const INGREDIENTS_FETCH_SUCCESS = "INGREDIENTS_FETCH_SUCCESS";

export const ADD_PRICE = "ADD_PRICE";
export const REDUCE_PRICE = "REDUCE_PRICE";
export const RESET_PRICE = "RESET_PRICE";

export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_ERROR = "PURCHASE_ERROR";
export const ORDER_IS_POSTING = "ORDER_IS_POSTING";
export const ORDER_IS_POSTED = "ORDER_IS_POSTED";
export const PURCHASE_INIT = "PURCHASE_INIT"

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
