export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const REMOVE_ALL_INGREDIENTS = "REMOVE_ALL_INGREDIENTS";

export const ADD_PRICE = "ADD_PRICE";
export const REDUCE_PRICE = "REDUCE_PRICE";
export const RESET_PRICE = "RESET_PRICE";
